esp_toml_version = 1.0

firmware_images_url = "https://esp.eterill.xyz/image/"

supported_apps = ["fsender-eyeos","szy-s3","szy-s3s","szy-s3-nobat","szy-pc","szy-pc-homekit","szy-plus","szy-plusm"]

[fsender-eyeos]
optionname = "小影EyeOS固件"
chipsets = ["ESP32-S3"]
image.esp32-s3 = "eyeos.bin"
readme.text = "https://esp.eterill.xyz/image/eyeos_readme.md"

[szy-s3]
optionname = "大叔神之眼S3圆形"
chipsets = ["ESP32-S3"]
developKits.esp32-s3 = ["s3-n8r2", "s3-n8r8"]
offset = "0x10000"
image.s3-n8r2 = "szy_s3_r2.bin"
image.s3-n8r8 = "szy_s3.bin"

[szy-s3s]
optionname = "大叔神之眼S3方形"
chipsets = ["ESP32-S3"]
developKits.esp32-s3 = ["s3-n8r2", "s3-n8r8"]
offset = "0x10000"
image.s3-n8r2 = "szy_s3s_r2.bin"
image.s3-n8r8 = "szy_s3s.bin"

[szy-s3-nobat]
optionname = "大叔神之眼S3无NTC电池"
chipsets = ["ESP32-S3"]
developKits.esp32-s3 = ["s3-n8r8"]
offset = "0x10000"
image.s3-n8r8 = "szy_s3_nobat.bin"

[szy-pc]
optionname = "大叔神之眼PCWiFi"
chipsets = ["ESP32-S3"]
developKits.esp32-s3 = ["s3-n8r2", "s3-n8r8"]
offset = "0x10000"
image.s3-n8r2 = "szy_pc_r2.bin"
image.s3-n8r8 = "szy_pc.bin"

[szy-pc-homekit]
optionname = "大叔神之眼PCHomeKit"
chipsets = ["ESP32-S3"]
developKits.esp32-s3 = ["s3-n8r2", "s3-n8r8"]
offset = "0x10000"
image.s3-n8r2 = "szy_pc_homekit_r2.bin"
image.s3-n8r8 = "szy_pc_homekit.bin"

[szy-plus]
optionname = "大叔神之眼PLUS"
chipsets = ["ESP32-S3"]
developKits.esp32-s3 = ["博虎新屏", "博虎旧屏", "华显屏"]
image.博虎新屏 = "szy_plus_bh.bin"
image.博虎旧屏 = "szy_plus_bhold.bin"
image.华显屏 = "szy_plus_hx.bin"

[szy-plusm]
optionname = "大叔神之眼PLUS改版"
chipsets = ["ESP32-S3"]
developKits.esp32-s3 = ["博虎新屏", "博虎旧屏", "华显屏"]
image.博虎新屏 = "szy_plusm_bh.bin"
image.博虎旧屏 = "szy_plusm_bhold.bin"
image.华显屏 = "szy_plusm_hx.bin"
