esp_toml_version = 1.0

# Base URL of the file server where the images are available
firmware_images_url = "https://adwait-esp.github.io/flasher/images/"

supported_apps = ["Matter-All Clusters App TE9", "Matter-Lighting App TE9"]

[Matter-All Clusters App TE9]
chipsets = ["ESP32", "ESP32-C3"]
image.esp32 = "esp32_matter_all-clusters-app.bin"
image.esp32-c3 = "esp32c3_matter_all-clusters-app.bin"
ios_app_url = ""
android_app_url = ""

[Matter-Lighting App TE9]
chipsets = ["ESP32", "ESP32-C3"]
image.esp32 = "esp32_matter_lighting-app.bin"
image.esp32-c3 = "esp32c3_matter_lighting-app.bin"
ios_app_url = ""
android_app_url = ""
